Adding bf-http-status and adding additional options to bf-test-url

diff --git a/overlay/usr/local/bin/bf-test-url b/overlay/usr/local/bin/bf-test-url
--- a/overlay/usr/local/bin/bf-test-url
+++ b/overlay/usr/local/bin/bf-test-url
@@ -4,17 +4,61 @@ set -euo pipefail
 
 
 #======================================================================================================================
-# Check argument.
-#   1   URL to test
+# Executable usage.
 #======================================================================================================================
 
-[[ -z "${1-}" ]] && bf-error "You must provide a URL to test." "bf-test-url"
-URL=${1}
+usage () {
+    echo "Usage: `basename ${0}` -m full|simple URL" 2>&1
+    echo
+    echo "    -m    Either 'full' (checks HTTP status) or 'simple' (default)."
+    echo "    -h    Show this usage message."
+    exit 2
+}
+
+while getopts ":hm:" C ; do
+    case ${C} in
+        m) MODE="${OPTARG}" ;;
+        ?) bf-notok "Invalid option: -${OPTARG}" "bf-test-url" && usage ;;
+    esac
+done
+
+shift $(($OPTIND -1))
+
+URL="${1-}"
+[[ -z "${URL-}" ]] && bf-error "You must provide the URL to test." "bf-test-url"
 
 
 #======================================================================================================================
 # Attempt to load the URL using wget.
 #======================================================================================================================
 
-bf-debug "Loading ${URL}." "bf-test-url"
-wget --no-verbose --spider --tries=1 "${URL}" || exit 1
+if [ "${MODE-}" = "simple" ] ; then
+
+    bf-debug "Loading ${URL}." "bf-test-url"
+    wget --no-verbose --spider --tries=1 "${URL}" || exit 1
+
+elif [ "${MODE-}" = "full" ] ; then
+
+    # get status
+    STATUS=$(bf-http-status "${URL}" || true)
+
+    # if STATUS is not a number, something went wrong loading the URL
+    if echo "${STATUS}" | grep -q '^[0-9]+$' ; then
+        bf-error "Unable to load ${URL}." "bf-test-url"
+    fi
+
+    # output the status and result
+    bf-debug "Status ${STATUS}:"
+    if [ "${STATUS}" -ge 200 ] && [ "${STATUS}" -le 399 ] ; then
+        bf-debug "  OK." "bf-test-url"
+    elif [ "${STATUS}" -ge 400 ] && [ "${STATUS}" -le 499 ] ; then
+        bf-error "  content error." "bf-test-url"
+    else
+        bf-error "  error." "bf-test-url"
+    fi
+
+else
+
+    bf-error "Unknown mode: ${MODE-}" "bf-test-url"
+
+fi
