Do readme push directly

diff --git a/.github/workflows/update-readme.yml b/.github/workflows/update-readme.yml
--- a/.github/workflows/update-readme.yml
+++ b/.github/workflows/update-readme.yml
@@ -11,19 +11,28 @@ jobs:
     steps:
       -
         name: Get repository name
-        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | sed "s/bfren\/docker-//")"  >> $GITHUB_ENV
+        run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | sed "s/bfren\/docker-//")" >> $GITHUB_ENV
         shell: bash
       -
         name: Checkout code
         uses: actions/checkout@v3
       -
-        name: Login to DockerHub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      -
         name: Push README
-        uses: christian-korneck/update-container-description-action@v1
-        with:
-          destination_container_repo: bfren/${{ env.REPOSITORY_NAME }}
+        run: |
+          TOKEN=$(curl -s -X POST \
+            -H "Content-Type: application/json" \
+            -d '{"username": "${{ secrets.DOCKERHUB_USERNAME }}", "password": "${{ secrets.DOCKERHUB_TOKEN }}"}' \
+            https://hub.docker.com/v2/users/login/ | jq -r .token) ; \
+          CODE=$(jq -n --arg MSG "$(< README.md)" \
+            '{"registry":"registry-1.docker.io","full_description": $MSG }' | \
+                curl -s -o /dev/null  -L -w "%{http_code}" \
+                  https://hub.docker.com/v2/repositories/"${{ env.REPOSITORY_NAME }}"/ \
+                  -d @- -X PATCH \
+                  -H "Content-Type: application/json" \
+                  -H "Authorization: JWT ${TOKEN}") ; \
+          if [[ "${CODE}" = "200" ]] ;
+          then \
+            echo "Successfully pushed README.md to Docker Hub" ; \
+          else \
+            printf "Unable to push README.md to Docker Hub, the response code was: %s\n" "${CODE}" && exit 1 ; \
+          fi
